// default package
// Generated 14 juin 2018 10:21:15 by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PaiementId generated by hbm2java
 */
@Embeddable
public class PaiementId implements java.io.Serializable {

	private int salonId;
	private int utilisateurId;

	public PaiementId() {
	}

	public PaiementId(int salonId, int utilisateurId) {
		this.salonId = salonId;
		this.utilisateurId = utilisateurId;
	}

	@Column(name = "salon_id", nullable = false)
	public int getSalonId() {
		return this.salonId;
	}

	public void setSalonId(int salonId) {
		this.salonId = salonId;
	}

	@Column(name = "utilisateur_id", nullable = false)
	public int getUtilisateurId() {
		return this.utilisateurId;
	}

	public void setUtilisateurId(int utilisateurId) {
		this.utilisateurId = utilisateurId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PaiementId))
			return false;
		PaiementId castOther = (PaiementId) other;

		return (this.getSalonId() == castOther.getSalonId())
				&& (this.getUtilisateurId() == castOther.getUtilisateurId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getSalonId();
		result = 37 * result + this.getUtilisateurId();
		return result;
	}

}
